version: "3.7"
services:
    www:
        build: .
        container_name: typo
        ports: 
            - "80:80"
            - "8022:22"
        links:
            - db
        networks:
            - default
        stdin_open: true
        tty: true

        environment:
            MYSQL_DATABASE: myDB
            MYSQL_USER: 0ppr2s  
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        
    db:
        image: mysql:5.6.51
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            MYSQL_DATABASE: myDB
            MYSQL_USER: 0ppr2s  
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456

        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        networks:
            - default
        environment:
            MYSQL_USER: myDB
            MYSQL_PASSWORD: 0ppr2s
            MYSQL_ROOT_PASSWORD: 123456
networks: 
    default:
